/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "dtu.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SubMsg1, SubMsg1, 2)


PB_BIND(SubMsg2, SubMsg2, AUTO)


PB_BIND(SubMsg3, SubMsg3, 4)


PB_BIND(SubMsg4, SubMsg4, 2)


PB_BIND(SubMsg5, SubMsg5, 2)


PB_BIND(OneOfMessage, OneOfMessage, 4)





