#ifndef _XTIMER_CONFIG_H
#define _XTIMER_CONFIG_H

#include "xparameters.h"

#define XTICKTIMER_IS_AXITIMER
#define XTICKTIMER_DEVICEID XPAR_AXI_TIMER_0_DEVICE_ID
#define XTIMER_IS_DEFAULT_TIMER

#endif /* XTIMER_CONFIG_H */
